### PR TITLE
Feature/tab swapping and date selection

### PR DESCRIPTION
**Pull request by danielcurtin**
Added base level tab swapping functionality between the New Booking screen and User Profile screen, (hopefully) fully fleshed out sorting on the customers bookings side so it should be pretty transferrable to the new booking side, it's really a mess in there right now so definitely need to look into cleaner approaches in the future but for now I'm pretty satisfied with functionality. Still need to get the all bookings loaded into the other screen, probably should add a "date available > xx/yy/zzzz" to the new booking screen cards.

### CODE REVIEW

**Comment by danielcurtin** [comment]
Also forgot to mention the changes made broke Customer-tests pretty bad so they should be fixed soon

**Comment by mrlobatoman** [comment]
Nice work Daniel, looks of nice revisions in this PR. Out of curiosity, what was the reason for changing the allBookings property in your booking class and creating a whole hotel class?

Code is looking very dry, something I aspire to accomplish!

**Comment by danielcurtin** [comment]
> 

I went for a hotel class because I wanted to be able to access all bookings in a global sense with a hotel variable, and all of the customers bookings in a local sense, while accessing the filter methods so they weren't duplicated across classes. (This ended up being an unnecessary piece of functionality- I misinterpreted the goals for the user dashboard)

**Comment by mrlobatoman** [comment]
Gotchya, maybe a future revision would be to get rid of that unnecessary piece of functionality. Sorry I didn't revise sooner, its definitely no a viable option to start messing with the whole file a day before the project due date. Still.. looks good!

**Pull request merged**
